set echo ON
spool 'C:\cprg250s\BRTDB\Prototype_System\Report 3\Report_3_Output.txt'

SET LINESIZE 200

COLUMN SUPPLIER_NAME FORMAT A40

COLUMN EMAIL_ADDRESS FORMAT A40

COLUMN CITY FORMAT A20

SELECT
    S.SUPPLIER_NAME,
    S.EMAIL_ADDRESS,
    S.CITY,
    S.PROVINCE
FROM
    BRT_SUPPLIERS         S
    JOIN BRT_PRODUCT_SUPPLIERS PS
    ON S.SUPPLIER_ID = PS.SUPPLIER_ID
WHERE
    PS.PRODUCT_ID = 1001;

SELECT
    S.SUPPLIER_NAME,
    S.EMAIL_ADDRESS,
    S.CITY,
    S.PROVINCE
FROM
    BRT_SUPPLIERS         S
    JOIN BRT_PRODUCT_SUPPLIERS PS
    ON S.SUPPLIER_ID = PS.SUPPLIER_ID
WHERE
    PS.PRODUCT_ID = 4101;

spool OFF